### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by davegaeddert**

### CODE REVIEW

**Comment by pullapprover** [comment]
Approved

**Comment by pullapprover** [comment]
Approved

**Comment by davegaeddert** [comment]
Approved

**Comment by davegaeddert** [comment]
Approved

**Comment by davegaeddert** [comment]
Approved

**Comment by davegaeddert** [comment]
Approved

**Comment by davegaeddert** [comment]
Approved

**Comment by davegaeddert** [comment]
Approved

**Comment by davegaeddert** [comment]
Approved

**Comment by davegaeddert** [comment]
Approved

**Comment by davegaeddert** [comment]
Approved

**Comment by davegaeddert** [comment]
Approved

**Comment by davegaeddert** [comment]
Rejected

**Comment by davegaeddert** [comment]
Approved

**Pull request closed without merging**
